### ISSUE TITLE
saf convert:asff2hdf backward compatible with tagged fix and check text

### ISSUE THREAD

**Issue by ejaronne** [mitre/saf#112]
I can't find the same code in the saf-cli, but since this is expecting fix to be a description label, it also needs to be able to look for it in a tag:fix since older profiles used tags for check and fix text.

https://github.com/mitre/hdf2asff/blob/c1827b8bf7cf591121a2286fd1b0c6e55c45a9c0/src/index.ts#L168

**Comment by camdenmoors** [comment]
This is part of the asff reverse mapper at https://github.com/mitre/heimdall2/blob/master/libs/hdf-converters/src/converters-from-hdf/asff/transformers.ts#L493 and https://github.com/mitre/heimdall2/blob/master/libs/hdf-converters/src/converters-from-hdf/asff/transformers.ts#L299

Does this require further changes?

**Comment by camdenmoors** [comment]
Closing as asff2hdf supports both descriptions and tags for fix and check text.
