### ISSUE TITLE
feat: inspec2ckl & inspec2xccdf

### ISSUE THREAD

**Issue by HerbBoy** [mitre/saf#1147]
Hi,

A feature I think that would be quite valuable is to re-add what was apart of https://github.com/mitre/inspec_tools which was seemingly dropped when merged into saf.

If more information is necessary id be happy to expand. But this would be a definite value add to many.

**Comment by aaronlippold** [comment]
This capability was to create an XCCDF Benchmark XML file ( which you could review in STIGViewer) from an HDF Profile JSON ( sans results ). This does not create an XCCDF-Results file from an HDF Results JSON file ( aka an inspec run )

For DOD / EMass DISA work - we usually use HDF Results JSON -> DISA Checklist 

All the the above workflow could of course be put back into the SAF CLI but just wondering what your use-cases are and what workflow you are looking to start.

**Comment by HerbBoy** [comment]
> 

I apologize for wasting time here. This was a lack of my understanding and HDF2XCCDF works as we need it to. Thank you for such a quick response.

Before i close this, I saw Emily pushed through a possible fix for a issue i had open, was wondering when the next release will be cut? Thanks in advance

**Comment by em-c-rod** [comment]
We plan releases every Tuesday, so it should be out tomorrow.

**Comment by HerbBoy** [comment]
thank you!

**Comment by aaronlippold** [comment]
@Amndeep7 @wdower and @em-c-rod hdf_results2ckl is something that should be released in the next sprint or two, hdf_profile2xccdf_benchmark and spreadsheet2xccdf_results and spreadsheet2disa_checklist should also be put back on the todo's for the next release after that.
