### ISSUE TITLE
xccdf to hdf results in empty code_desc

### ISSUE THREAD

**Issue by candrews** [mitre/saf#1163]
1. Download the Ubuntu 18.04 STIG from DISA at https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_CAN_Ubuntu_18-04_V2R8_STIG_SCAP_1-2_Benchmark.zip
2. Use openscap to generate an xccdf report: `oscap-podman ubuntu:18.04 xccdf eval --fetch-remote-resources --profile MAC-3_Public --report report.html --results results.xml U_CAN_Ubuntu_18-04_V2R8_STIG_SCAP_1-2_Benchmark.xml` For convenience, here's the resulting [results.xml](https://github.com/mitre/saf/files/10877270/results.xml.txt)
3. Use this project to convert the the xccdf results to hdf: `npx @mitre/saf convert xccdf_results2hdf -i results.xml -o results.hdf` For convenience, here's the resulting [results.hdf.json](https://github.com/mitre/saf/files/10877276/results.hdf.json.txt)

Actual:
Every instance of `code_desc` has a value of empty string, for example:
```json
"results": [
  {
    "status": "failed",
    "code_desc": "",
    "start_time": "2023-03-02T09:53:07-05:00"
  }
```

Expected:
`code_desc` should have value. Per the hdf documentation at https://github.com/mitre/saf/wiki/HDF-Mapper-and-Converter-Creation-Guide-(for-SAF-CLI-&-Heimdall2)#hdf-schema-breakdown- it should contain "Test expectations as defined by control"

**Comment by aaronlippold** [comment]
So you are trying to convert an oscap xccdf-results file to HDF-Results JSON. I would guess this is likely a bug with the nesting of the XML given the results may be pulling that code_desc from a key that may being missed by the mapper. 

We would be happy to chat with you about this to see if we can dig into what is causing the mapping issue and get a PR started.

**Comment by candrews** [comment]
> We would be happy to chat with you about this to see if we can dig into what is causing the mapping issue and get a PR started.

Sounds great! Is there more information I can provide?

**Comment by aaronlippold** [comment]
So I think what we are looking for here is that the XCCDF-Results file actually has the rendered SCAP - vs just a reference to an SCAP XML File - in the final object that we are looping over to create the HDF-Results JSON. If we are - for some reason - missing the step that populates the 'SCAP code' that would be the expected 'code of the test' we expect to be put there. I think we just have to dig in a bit with the debugger. 

Does this describe what you are expecting so we are clear on the expected path.

**Comment by candrews** [comment]
I admit that I don't understand all of those details. Basically, I'm looking for the steps I provided in this issue's description to produce an HDF file that has `code_desc` populated. I'm not knowledgeable enough (yet?) to know exactly how that should be done or why it's not being done today.

**Comment by candrews** [comment]
@aaronlippold is there anything I can do to help this effort?

**Comment by candrews** [comment]
It appears this bug is in `@mitre/hdf-converters`, and I found the source for that package at https://github.com/mitre/heimdall2/tree/master/libs/hdf-converters

**Comment by candrews** [comment]
Since https://github.com/mitre/heimdall2/pull/4255 now merged, the remaining task is to upgrade to `@mitre/hdf-converters` version 2.6.58 once it is released.

**Comment by Amndeep7** [comment]
A release has gone out so I'm going to close this issue @candrews.  Ping me if you want it to remain open for some reason.
