### ISSUE TITLE
Generating Checklist with convert hdf2ckl does not produce a valid CKL file in 1.2.7

### ISSUE THREAD

**Issue by rlakey** [mitre/saf#1238]
Given a json result from https://github.com/vmware/dod-compliance-and-automation/tree/master/vsphere/7.0/vsphere/inspec/vmware-vsphere-7.0-stig-baseline as an example.

The output of `saf convert hdf2ckl -i .\saftestckl.json -o saftestckl.ckl` does not produce a valid CKL file.

The Vul ID, Rule ID, Rule Name, and STIG ID fields are not correctly populated even though the appropriate tags exist in the InSpec profile and the json output.

<img width="653" alt="image" src="https://user-images.githubusercontent.com/14838339/227243435-9c1a7ec8-196d-4e12-bf7a-8b172b40eb58.png">

For comparison exporting the same result from Heimdall 2.6.38 correctly fills everything out except Vul ID.

<img width="535" alt="image" src="https://user-images.githubusercontent.com/14838339/227243998-14439942-ddcf-4487-ae06-493d02cf7d5b.png">

Validate checklists must also be disabled in STIG Viewer 2.17 to import the saf CKL.

**Comment by rlakey** [comment]
I also tried the build from [here](https://github.com/mitre/saf/actions/runs/4412036337).

Vul ID is not properly populated and there is a lot of missing data. Only 11 controls are listed when it should be 28.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/14838339/227249604-626781df-a322-43fc-83ab-cd574705af21.png">

**Comment by HerbBoy** [comment]
@rlakey give hdf2xccdf a try (only thing, is ignore or rather the skipper or n/a finds by inspec will not be properly marked).
