### ISSUE TITLE
Additions of Microsoft Secure Score Artifact Support for HDF Converters

### ISSUE THREAD

**Issue by kdkir** [mitre/saf#2564]
Microsoft Secure Score is a measurement of an organization's security posture, with a higher number indicating more recommended actions taken. Information can be found at [Microsoft Secure Score](https://learn.microsoft.com/en-us/defender-xdr/microsoft-secure-score).

The addition of support for Microsoft Secure score would allow for users of SAF to assess the security posture of Microsoft tenants against vendor published best practices. A JSON representation of the secure score report can be generated by security and compliance administrators of a Microsoft Tenant. 

Attached is an example of the Secure Score JSON file, notated with potential mappings to the HDF schema. I would greatly appreciate the chance to discuss this potential new converter with the SAF team. 
[ms365_sample.json](https://github.com/mitre/saf/files/15301460/ms365_sample.json)

**Comment by meme112233** [comment]
See https://github.com/mitre/heimdall2/pull/6007.  This PR performs the conversion (draft status).  PR for this issue in this repo supporting the SAF-CLI support is expected soon.

**Comment by Amndeep7** [comment]
@kdkir thanks for bringing up this mapper, and thanks to @meme112233 for implementing it.  If the current implementation does not meet your requirements, please make a new issue explaining what breaks.
