### ISSUE TITLE
Add a timeout on the e2e tests

### ISSUE THREAD

**Issue by Amndeep7** [mitre/saf#27]
<img width="1870" alt="image" src="https://user-images.githubusercontent.com/2015821/148503504-0a29bcde-7bd4-4261-8683-865584f84828.png">

Figure something's gone wrong if it's taking 25min+ to run these tests so just fail it.  In the above case, it's cause for some reason whatever `yarn test` actually resolves down to hangs when `ts-mocha --forbid-only "test/**/*.test.ts"` fails cause that command sometimes doesn't exit the process unless it's a success it seems (at least on my machine).

**Comment by Amndeep7** [comment]
Oh the hang is cause the xccdf file is huge so it took forever to render/write the diff.  IMO even more reason to have a timeout.

**Comment by camdenmoors** [comment]
Completed in https://github.com/mitre/saf/commit/7293b26c44dee145dba9f7cf11452714fa5afe24#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L110 (set 8 seconds)
