### ISSUE TITLE
BUG - TypeError: Cannot read properties of undefined (reading 'length') when converting HDF to CSV

### ISSUE THREAD

**Issue by RLI-Rdeaton** [mitre/saf#2925]
**Describe the bug**
```
Currently when attempting to convert a seemingly valid XCCDF file from oscap-docker, an error occurs.  This happens on 1.4.15 of saf

/ # saf convert hdf2csv -i openscap-report.hdf.json -o report.csv -t
/usr/local/lib/node_modules/@mitre/saf/lib/commands/convert/hdf2csv.js:34
                if ((row[key]).length > 32767) {
                               ^

TypeError: Cannot read properties of undefined (reading 'length')
    at /usr/local/lib/node_modules/@mitre/saf/lib/commands/convert/hdf2csv.js:34:32
    at Array.map (<anonymous>)
    at HDF2CSV.run (/usr/local/lib/node_modules/@mitre/saf/lib/commands/convert/hdf2csv.js:31:21)
    at async HDF2CSV._run (/usr/local/lib/node_modules/@mitre/saf/node_modules/@oclif/core/lib/command.js:301:22)
    at async Config.runCommand (/usr/local/lib/node_modules/@mitre/saf/node_modules/@oclif/core/lib/config/config.js:424:25)
    at async Object.run (/usr/local/lib/node_modules/@mitre/saf/node_modules/@oclif/core/lib/main.js:95:16)
```

**To Reproduce**
1. Get a hold of the chainguard profile from https://github.com/chainguard-dev/stigs .
2. Use docker-oscap to perform an analysis, E.G.:
```
oscap-docker image "chainguard/wolfi-base:latest" xccdf eval --verbose ERROR --fetch-remote-resources --profile "xccdf_basic_profile_.check" --results "openscap-report.xml" --report "opensca
p-report.html" "ssg/stigs-0.1.2/gpos/xml/scap/ssg/content/ssg-chainguard-gpos-ds.xml"

```
3. Use SAF to convert the results to HDF, E.G.:
`saf convert xccdf_results2hdf -i "openscap-report.xml" -o openscap-report.hdf`

4. Use SAF to convert the HDF to CSV, E.G.:
`saf convert hdf2csv -i openscap-report.hdf.json -o report.csv -t`

**Expected behavior**
I expect SAF to convert the file into a HDF file, and then into a CSV.  I expect the CSV to be valid.

**Additional context**

I am attaching the XCCDF file that gets generated from the Wolfi STIG artifacts as well as the HDF file that is generated.

[example.hdf.json](https://github.com/user-attachments/files/17198148/example.hdf.json)
[example XCCDF.zip](https://github.com/user-attachments/files/17198163/example.XCCDF.zip)

**Comment by aaronlippold** [comment]
If you load the report into https://heimdall-lite.mitre.org and then use the Heimdall Lite export to CSV do you see the same error?

**Comment by aaronlippold** [comment]
Yup, heimdall export works clean it seems. Odd. Thanks for uploading your samples to make debug easier :) 👍🏻

**Comment by RLI-Rdeaton** [comment]
I do not see the same error, which is super interesting.  I'm ultimately looking to build this into a pipeline for reporting to a security dashboard for compliance.

**Comment by RLI-Rdeaton** [comment]
This same data is actually breaking the microsoft sarif tools as well; it's been a real fun couple of days trying to get this into a format I can use!

**Comment by aaronlippold** [comment]
Yup, grok you completely, just needed to ask. 

I will ask the team to take a look to see if we can find out what is throwing a NULL in the converstion which is usually what these kinds of errors come down to.

You could just convert your SCAP to an inspec profile which would likely not be as difficult to maintain ... ( :) ) ... problem solved.

**Comment by RLI-Rdeaton** [comment]
Oh that's something I hadn't considered, let me see what I can do there.  Thanks a ton for the ideas.

**Comment by georgedias** [comment]
I'm working the issue, found the problem, will have it done tomorrow.

**Comment by georgedias** [comment]
PR merged into main

**Comment by georgedias** [comment]
Fix will be included on the next SAF CLI release.
