### ISSUE TITLE
Running in Docker container Permission Denied - RHEL

### ISSUE THREAD

**Issue by anton-skyward** [mitre/saf#31]
Running docker container in RHEL without "--privileged" getting (/usr/local/bundle/gems/heimdall_tools-1.3.37/lib/heimdall_tools/cli.rb:22:in `read': Permission denied @ rb_sysopen - input.json (Errno::EACCES)) even if the input.json with 777

**Comment by Amndeep7** [comment]
Closing due to this being a different container.  Please reopen if this issue is still applicable to the saf cli.
