### ISSUE TITLE
Zap2HDF Converter Issue

### ISSUE THREAD

**Issue by rajakrish** [mitre/saf#334]
We are using OWASPZAP and used Zap-API to capture the OWASPZAP results in JSON format. We used this JSON file as the input to convert to HDF and it is not converting properly. I have attached both the input and the output files (had to change them to txt files since JSON is not supported) here:
[input.txt](https://github.com/mitre/saf/files/8563614/input.txt)
[output.txt](https://github.com/mitre/saf/files/8563615/output.txt)

The command used for conversion: 
saf convert zap2hdf -i input.json -n test.com -o output.json

**Comment by camdenmoors** [comment]
Hi,

Thanks for your report. Please try with `saf convert zap2hdf -i input.json -o test-dashboard.json --name https://test-dashboard.com` and `saf convert zap2hdf -i input.json -o test.json --name https://test.com`.

**Comment by rajakrish** [comment]
That worked perfectly. I now understand the parameters much better. Thanks for your prompt response. I really appreciate it.
