### ISSUE TITLE
GitHub Pages - SSL Configuration

### ISSUE THREAD

**Issue by aaronlippold** [mitre/saf#35]
See: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages#https-errors

**Comment by aaronlippold** [comment]
The other SAF sites are configured so the automatic SSL works. We likely have to have the MITRE DNS folks update something in the CNAME or ANAME record.

**Comment by camdenmoors** [comment]
SSL Configuration is now setup, and is now available at https://saf-cli.mitre.org
