### ISSUE TITLE
saf utils {passthrough,target} {read,write} support

### ISSUE THREAD

**Issue by ejaronne** [mitre/saf#581]
add a submodule to 'apply' that either adds a data object to the .passthrough or to the .target root element

`saf attest apply passthrough -i existing.hdf --passthrough-data [file || object] -o output.hdf`

`saf attest apply target -i --target-data -o ...`

it will overwrite existing objects

add a `read` which will 'return the data currently in':

`saf attest read passthrough -i myfile`

`saf attest read target -i myfile`

**Comment by aaronlippold** [comment]
In talking with @camdenmoors we agreed that the primary method on these should be `utils` rather than under the `attest` area. 

The function name of either `apply` or `write` is still open to debate.

```bash

# utilities for working with HDF Passthough data 

saf utils passthrough read -i myfile -o my_passthrough.json
saf utils passthrough apply|write -i existing.hdf --passthrough-data [file || object] -o output.hdf

# utilities for working with HDF Target data

saf utils target read -i myfile -o my_target.json
saf utils target apply|write -i --target-data -o ...
```
