### ISSUE TITLE
bug: saf generate delta removes custom content resulting in execution failure

### ISSUE THREAD

**Issue by HerbBoy** [mitre/saf#997]
## Describe the bug

saf generate v1.2.2 deletes custom content from controls during a metadata update. It appears the logic is designed to ignore anything prior to a describe block (now im not certain of this but it appears that way). Which if this is the case removes the ability to declare variables etc.

## To Reproduce

1. `podman pull mitre/saf:latest`
2. `podman run --rm -it --entrypoint bash -v$(pwd):/share mitre/saf`
4. `saf generate delta -J profile.json -X U_RHEL_8_STIG_V1R8_Manual-xccdf.xml -o new/ -L debug`
5. See below error:

## Expected behavior
For this function to populate updated metadata without removing the check logic (aka custom content).

### What actually is removed for the skimmers (full file content below)
```RUBY
  umask_regexp = /umask\s*(?<umask_code>\d\d\d)/

  bashrc_umask = file('/etc/bashrc').content.match(umask_regexp)[:umask_code]
  cshrc_umask = file('/etc/csh.cshrc').content.match(umask_regexp)[:umask_code]

  if bashrc_umask == '000' || cshrc_umask == '000'
    impact 0.7
    tag severity: 'high'
```

### Before `saf generate delta` is run
```RUBY
control 'SV-230385' do
  title 'RHEL 8 must define default permissions for logon and non-logon shells.'
  desc  "The umask controls the default access mode assigned to newly created
files. A umask of 077 limits new files to mode 600 or less permissive. Although
umask can be represented as a four-digit number, the first digit representing
special access modes is typically ignored or required to be \"0\". This
requirement applies to the globally configured system defaults and the local
interactive user defaults for each account on the system."
  desc  'rationale', ''
  desc  'check', "
    Verify that the umask default for installed shells is \"077\".

    Check for the value of the \"UMASK\" parameter in the \"/etc/bashrc\" and
\"/etc/csh.cshrc\" files with the following command:

    Note: If the value of the \"UMASK\" parameter is set to \"000\" in either
the \"/etc/bashrc\" or the \"/etc/csh.cshrc\" files, the Severity is raised to
a CAT I.

    # grep -i umask /etc/bashrc /etc/csh.cshrc

    /etc/bashrc:          umask 077
    /etc/bashrc:          umask 077
    /etc/csh.cshrc:      umask 077
    /etc/csh.cshrc:      umask 077

    If the value for the \"UMASK\" parameter is not \"077\", or the \"UMASK\"
parameter is missing or is commented out, this is a finding.
  "
  desc 'fix', "
    Configure the operating system to define default permissions for all
authenticated users in such a way that the user can only read and modify their
own files.

    Add or edit the lines for the \"UMASK\" parameter in the \"/etc/bashrc\"
and \"etc/csh.cshrc\" files to \"077\":

    UMASK 077
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-OS-000480-GPOS-00227'
  tag gid: 'V-230385'
  tag rid: 'SV-230385r627750_rule'
  tag stig_id: 'RHEL-08-020353'
  tag fix_id: 'F-33029r567902_fix'
  tag cci: ['CCI-000366']
  tag nist: ['CM-6 b']

  umask_regexp = /umask\s*(?<umask_code>\d\d\d)/

  bashrc_umask = file('/etc/bashrc').content.match(umask_regexp)[:umask_code]
  cshrc_umask = file('/etc/csh.cshrc').content.match(umask_regexp)[:umask_code]

  if bashrc_umask == '000' || cshrc_umask == '000'
    impact 0.7
    tag severity: 'high'
  end

  describe 'umask value defined in /etc/bashrc' do
    subject { bashrc_umask }
    it { should cmp '077' }
  end
  describe 'umask value defined in /etc/csh.cshrc' do
    subject { cshrc_umask }
    it { should cmp '077' }
  end
end
```

### After `saf generate delta` is run
```RUBY
control 'SV-230385' do
  title 'RHEL 8 must define default permissions for logon and non-logon shells.'
  desc 'The umask controls the default access mode assigned to newly created
files. A umask of 077 limits new files to mode 600 or less permissive. Although
umask can be represented as a four-digit number, the first digit representing
special access modes is typically ignored or required to be "0". This
requirement applies to the globally configured system defaults and the local
interactive user defaults for each account on the system.'
  desc 'check', 'Verify that the umask default for installed shells is "077".

Check for the value of the "UMASK" parameter in the "/etc/bashrc", "/etc/csh.cshrc" and "/etc/profile" files with the following command:

Note: If the value of the "UMASK" parameter is set to "000" in the "/etc/bashrc" the "/etc/csh.cshrc" or the "/etc/profile" files, the Severity is raised to a CAT I.

# grep -i umask /etc/bashrc /etc/csh.cshrc /etc/profile

/etc/bashrc:          umask 077
/etc/bashrc:          umask 077
/etc/csh.cshrc:      umask 077   
/etc/csh.cshrc:      umask 077
/etc/profile:      umask 077   
/etc/profile:      umask 077

If the value for the "UMASK" parameter is not "077", or the "UMASK" parameter is missing or is commented out, this is a finding.'
  desc 'fix', 'Configure the operating system to define default permissions for all authenticated users in such a way that the user can only read and modify their own files.

Add or edit the lines for the "UMASK" parameter in the "/etc/bashrc", "/etc/csh.cshrc" and "/etc/profile"files to "077":

UMASK 077'
  impact 0.5
  ref 'DPMS Target Red Hat Enterprise Linux 8'
  tag severity: 'medium'
  tag gtitle: 'SRG-OS-000480-GPOS-00227'
  tag gid: 'V-230385'
  tag rid: 'SV-230385r792902_rule'
  tag stig_id: 'RHEL-08-020353'
  tag fix_id: 'F-33029r792901_fix'
  tag cci: ['CCI-000366']
  tag nist: ['CM-6 b']

  end

  describe 'umask value defined in /etc/bashrc' do
    subject { bashrc_umask }
    it { should cmp '077' }
  end
  describe 'umask value defined in /etc/csh.cshrc' do
    subject { cshrc_umask }
    it { should cmp '077' }
  end
end
```

## Environment

- OS: Rocky8
- Podman version:  4.1.1
- SAF version [1.2.2](https://github.com/mitre/saf/releases/tag/1.2.2)

**Comment by aaronlippold** [comment]
We will add a few unit tests to make sure the top, between, and bottom of the describe / ruby code is all caputred.

**Comment by HerbBoy** [comment]
This is still a issue in the latest release, can this be re-opened? or should a new issue be made? @aaronlippold

**Comment by HerbBoy** [comment]
```bash
saf --version:
@mitre/saf/1.2.6 linux-x64 node-v16.19.1
```

![image](https://user-images.githubusercontent.com/61263592/223493463-6e05b7b7-23c7-41c7-8537-52af9e056c93.png)

Resulting in the same syntax error as the block of code before a describe block was removed. Though it is not as rampant as before this is just the first file i have found after updating and running a quick test (this was the one it complained about).

```
/opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/profile_context.rb:171:in `instance_eval': redhat-enterprise-linux-8-stig-baseline/controls/SV-230385.rb:51: syntax error, unexpected `end', expecting end-of-input (SyntaxError)
```

**Comment by em-c-rod** [comment]
I see that the dependency in the SAF CLI updated right after the release was done. https://github.com/mitre/saf/commit/48cf40a9a49b29cf0a4f8bf9b5180a4beeff32f7. You can clone and build locally for the fix or wait for the release this week. Thanks for participating in the security community so we can continue to enhance the processes. Let us know if there are outstanding issues after that.

**Comment by HerbBoy** [comment]
> I see that the dependency in the SAF CLI updated right after the release was done. [48cf40a](https://github.com/mitre/saf/commit/48cf40a9a49b29cf0a4f8bf9b5180a4beeff32f7). You can clone and build locally for the fix or wait for the release this week. Thanks for participating in the security community so we can continue to enhance the processes. Let us know if there are outstanding issues after that.

will give it a shot. thank you

**Comment by HerbBoy** [comment]
A issue still is persisting, i thought i had just messed up my manual build so i waited for the build published yesterday and the updating of meta content remains problematic.

```
/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.12.2/lib/inspec/profile_context.rb:171:in `instance_eval': redhat-enterpris
e-linux-8-stig-baseline/controls/SV-230336.rb:62: syntax error, unexpected tLABEL (SyntaxError)
    Note: If the System Administrator ...
    ^~~~~
redhat-enterprise-linux-8-stig-baseline/controls/SV-230336.rb:67: syntax error, unexpected ':'
    Note: This check applies to RHEL v...
        ^
redhat-enterprise-linux-8-stig-baseline/controls/SV-230336.rb:67: syntax error, unexpected ',', expecting `end'
...s to RHEL versions 8.0 and 8.1, if the system is
...                              ^
redhat-enterprise-linux-8-stig-baseline/controls/SV-230336.rb:68: syntax error, unexpected ',', expecting `end'
RHEL version 8.2 or newer, this check is not applicable.
                         ^
redhat-enterprise-linux-8-stig-baseline/controls/SV-230336.rb:68: syntax error, unexpected local variable or method, expecting '('
...r, this check is not applicable.
...                     ^~~~~~~~~~
redhat-enterprise-linux-8-stig-baseline/controls/SV-230336.rb:70: `$' without identifiers is not allowed as a global variable name
    $ sudo grep pam_faillock.so /et...
    ^~
redhat-enterprise-linux-8-stig-baseline/controls/SV-230336.rb:70: unknown regexp options - pa
...o grep pam_faillock.so /etc/pam.d/password-auth
...                           ^~~~
redhat-enterprise-linux-8-stig-baseline/controls/SV-230336.rb:72: unknown regexp options - lg
```

An example w/ vscode showing a better picture of the syntax (what i assume is simply how items are indented)
![image](https://user-images.githubusercontent.com/61263592/224431915-fa209c46-460b-406c-bce5-e1f901ee3989.png)

**Comment by em-c-rod** [comment]
I see. Thank you for bringing this up. Incorporating handling of inputs in metadata has been on our radar, but we hadn't prioritized the implementation of that yet. We can track this at this existing issue and generate activity for implementation. We'll need to generate a pattern for this. https://github.com/mitre/saf/issues/770

**Comment by HerbBoy** [comment]
I am not sure what you mean by inputs? The image above is showing how delta updates meta content but does not properly keep indentation causing basic syntax errors? Or am i missing something?

**Comment by aaronlippold** [comment]
A new issue would be helpful but also links to the profiles you are seeing the issue in and the XCCDF file you are using for detla. 

We would also be happy to get on a Zoom with you to do a bit of show and tell troubleshooting to help get agreement on the issue as well.

**Comment by karikarshivani** [comment]
Hey @HerbBoy, would you be comfortable getting on a call with us? We can walk you through how inputs are being used in the STIG content (from the screenshot that you shared) and also get a better understanding of the issue you're coming across.
Here is the email: saf@groups.mitre.org

**Comment by HerbBoy** [comment]
apologies on the delayed response. I reached out via email as suggested.
